"""CSV + verified fragrance metadata -> standalone static-app catalog script."""

import argparse
import csv
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

BRANDS = [
    "BOADICEA THE VICTORIOUS", "STEPHANE HUMBERT LUCAS", "GOLDFIELD & BANKS",
    "FRAGRANCE DU BOIS", "ASTROPHIL & STELLA", "UNE NUIT NOMADE", "MAISON MATAHA",
    "ROYAL CROWN", "ROOM 1015", "BOIS 1920", "M.MICALLEF", "REINVENTED",
    "PANTHEON", "SOSPIRO", "ELLA K", "WIDIAN",
]


def product_identity(name):
    brand = next((value for value in BRANDS if name.startswith(value + " ")), "확인 전")
    title = name[len(brand):].strip() if brand != "확인 전" else name
    # Only strip a standalone trailing volume, never a multi-bottle pack (3x10ml).
    title = re.sub(r"\s+\d+(?:\.\d+)?\s*ml$", "", title, flags=re.IGNORECASE).strip()
    return "Goldfield & Banks" if brand == "GOLDFIELD & BANKS" else brand, title


def complete_enrichment(products, enrichment):
    assigned = set()
    for item in enrichment:
        overlap = assigned.intersection(item["product_ids"])
        if overlap:
            raise ValueError(f"Product IDs assigned twice: {overlap}")
        assigned.update(item["product_ids"])
    groups = {}
    for product in products:
        if product["product_id"] in assigned:
            continue
        identity = product_identity(product["name"])
        groups.setdefault(identity, []).append(product["product_id"])
    completed = [dict(item) for item in enrichment]
    # Extend existing auto-groups when new volumes appear in later scrapes.
    existing_groups = {(item["brand"], item.get("localName") or item["name"]): item
                       for item in completed}
    for (brand, name), product_ids in groups.items():
        if (brand, name) in existing_groups:
            existing_groups[(brand, name)]["product_ids"] = sorted(set(
                existing_groups[(brand, name)]["product_ids"] + product_ids))
            continue
        completed.append({
            "brand": "Goldfield & Banks" if brand == "GOLDFIELD & BANKS" else brand,
            "name": name, "localName": "", "product_ids": product_ids,
            "profile": "unknown", "accords": [], "accordBasis": "확인 전",
            "top": None, "middle": None, "base": None, "intro": None,
            "review": None, "source": None, "checkedAt": None,
        })
    return completed


def build_catalog(csv_path, enrichment_path):
    with csv_path.open(encoding="utf-8-sig", newline="") as file:
        rows = list(csv.DictReader(file))
    products = []
    seen = set()
    for row in rows:
        product_id = int(row["product_id"])
        if product_id in seen:
            continue
        seen.add(product_id)
        products.append({
            "product_id": product_id, "name": row["name"],
            "price": int(row["price"]) if row["price"] else None,
            "sold_out": row["sold_out"].lower() == "true",
            "product_url": row["product_url"], "image_url": row["image_url"],
        })
    by_id = {item["product_id"]: item for item in products}
    enrichment = json.loads(enrichment_path.read_text(encoding="utf-8"))
    enrichment = complete_enrichment(products, enrichment)
    recommendations = []
    for metadata in enrichment:
        verified = bool(metadata.get("source") and metadata.get("accords"))
        if metadata.get("profile") != "unknown" and not verified:
            raise ValueError(f"Missing scent source or accords: {metadata.get('name')}")
        variants = [by_id[product_id] for product_id in metadata["product_ids"] if product_id in by_id]
        if not variants:
            continue
        representative = next((item for item in variants if not item["sold_out"]), variants[0])
        recommendations.append({
            **metadata, "variants": variants,
            "description": metadata.get("intro") or "향 노트와 어코드: 확인 전. 아로코 상품 설명을 참고해 주세요.",
            "url": metadata.get("source") or representative["product_url"],
            "scentVerified": verified,
            "domesticUrl": representative["product_url"], "domesticLabel": "아로코 상품 보기",
            "soldOut": all(item["sold_out"] for item in variants), "catalogSource": "arokor",
        })
    return {"products": products, "recommendations": recommendations,
            "verifiedCount": sum(item["scentVerified"] for item in recommendations)}


def export_catalog(output_path, csv_path=ROOT / "data/arokor_products.csv",
                   enrichment_path=ROOT / "data/arokor_enrichment.json"):
    catalog = build_catalog(csv_path, enrichment_path)
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("// Generated by chapt999/export_arokor.py\nconst arokorCatalog = "
                           + json.dumps(catalog, ensure_ascii=False, indent=2) + ";\n", encoding="utf-8")
    return catalog


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=ROOT / "chapt999/app-integration/arokor-catalog.js")
    parser.add_argument("--sync-enrichment", action="store_true")
    args = parser.parse_args()
    if args.sync_enrichment:
        enrichment_path = ROOT / "data/arokor_enrichment.json"
        initial = build_catalog(ROOT / "data/arokor_products.csv", enrichment_path)
        metadata = [{key: value for key, value in item.items() if key in {
            "brand", "name", "localName", "product_ids", "profile", "accords", "accordBasis",
            "top", "middle", "base", "intro", "review", "source", "checkedAt",
        }} for item in initial["recommendations"]]
        enrichment_path.write_text(json.dumps(metadata, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    result = export_catalog(args.output)
    print(f"Products: {len(result['products'])}; recommendation groups: {len(result['recommendations'])}; verified: {result['verifiedCount']}")
